# Generated by Django 5.1.7 on 2025-06-26 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(help_text='Name of the opposing team', max_length=100)),
                ('date', models.DateTimeField(help_text='Date and time of the match')),
                ('venue', models.CharField(choices=[('HOME', 'Camp Nou (Home)'), ('AWAY', 'Away'), ('NEUTRAL', 'Neutral Venue')], default='HOME', max_length=20)),
                ('competition', models.CharField(choices=[('LA_LIGA', 'La Liga'), ('CHAMPIONS_LEAGUE', 'Champions League'), ('COPA_DEL_REY', 'Copa del Rey'), ('SUPERCOPA', 'Supercopa de España'), ('CLUB_WORLD_CUP', 'Club World Cup'), ('FRIENDLY', 'Friendly'), ('OTHER', 'Other')], default='LA_LIGA', max_length=20)),
                ('result', models.CharField(blank=True, help_text="Match result (e.g., '2-1', '0-0'). Leave blank for upcoming matches.", max_length=20, null=True)),
                ('summary', models.TextField(help_text='Match review for completed matches or preview for upcoming matches')),
                ('image_url', models.URLField(blank=True, help_text='URL of an image hosted externally (e.g., Imgur, CDN)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(help_text='Admin/user who posted this match', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-date'],
            },
        ),
    ]
