# Generated by Django 4.2.7 on 2025-06-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person commenting', max_length=100)),
                ('comment', models.TextField(help_text='The comment content', max_length=1000)),
                ('email', models.EmailField(blank=True, help_text='Optional email address (not displayed publicly)', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the commenter (for moderation)', null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the comment is approved for display')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(help_text='The match this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='matches.match')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', '-created_at'], name='matches_com_match_i_6a822e_idx'), models.Index(fields=['is_approved', '-created_at'], name='matches_com_is_appr_35cb83_idx')],
            },
        ),
    ]
