# Generated by Django 4.2.7 on 2025-06-26 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide post from public view'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(help_text='Post author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(help_text='Post content'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional post image', null=True, upload_to='community_posts/'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(help_text='Post title', max_length=200),
        ),
    ]
