# Generated by Django 5.1.7 on 2025-06-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Name of the player', max_length=100)),
                ('from_club', models.CharField(help_text='Club the player is transferring from', max_length=100)),
                ('to_club', models.CharField(default='FC Barcelona', help_text='Club the player is transferring to', max_length=100)),
                ('transfer_type', models.CharField(choices=[('RUMOR', 'Rumor'), ('CONFIRMED', 'Confirmed'), ('HISTORY', 'History')], help_text='Type of transfer (rumor, confirmed, or history)', max_length=10)),
                ('transfer_date', models.DateField(blank=True, help_text='Date when the transfer occurred or is expected to occur', null=True)),
                ('fee', models.CharField(blank=True, help_text="Transfer fee (e.g., '€50M', 'Free transfer', 'Loan')", max_length=50, null=True)),
                ('source', models.URLField(blank=True, help_text='Source URL for the transfer news', null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to player or transfer-related image', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the transfer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(help_text='User who posted this transfer information', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
