# Generated by Django 5.1.7 on 2025-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Player's full name", max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward'), ('SUB', 'Substitute')], help_text="Player's position on the field", max_length=3)),
                ('age', models.IntegerField(help_text="Player's age")),
                ('nationality', models.CharField(help_text="Player's nationality", max_length=50)),
                ('bio', models.TextField(blank=True, help_text="Player's biography and career highlights", null=True)),
                ('profile_image', models.ImageField(blank=True, help_text="Upload player's profile photo", null=True, upload_to='players/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
    ]
